name = "self-publishing-blog"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "DB"
database_name = "blog_db"
database_id = "8bd7c652-e7df-42af-af43-3403c93a2d9e"

[vars]
# Add Slack/Discord Webhooks here
# SLACK_WEBHOOK_URL = ""
# DISCORD_WEBHOOK_URL = ""

